// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFHMflsw3hvQA73fB6Ddm2nFGxtJI4qGY',
    appId: '1:413718822127:web:9b3737c57382292efdaf1a',
    messagingSenderId: '413718822127',
    projectId: 'eatfolio-a4334',
    authDomain: 'eatfolio-a4334.firebaseapp.com',
    storageBucket: 'eatfolio-a4334.firebasestorage.app',
    measurementId: 'G-1GGM1NX0L3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD06xT-HexZnNr9Nv1TddBKQuYwxB7Kyho',
    appId: '1:413718822127:android:82581e60c5594718fdaf1a',
    messagingSenderId: '413718822127',
    projectId: 'eatfolio-a4334',
    storageBucket: 'eatfolio-a4334.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOIyKvo40KN6GEC6clJIDJPK4pVEjgNIo',
    appId: '1:413718822127:ios:4705a64e3de20732fdaf1a',
    messagingSenderId: '413718822127',
    projectId: 'eatfolio-a4334',
    storageBucket: 'eatfolio-a4334.firebasestorage.app',
    iosClientId:
        '413718822127-7nq6gpfi7gg4dt9ns8ueaom8tgsa3hj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.eatfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOIyKvo40KN6GEC6clJIDJPK4pVEjgNIo',
    appId: '1:413718822127:ios:4705a64e3de20732fdaf1a',
    messagingSenderId: '413718822127',
    projectId: 'eatfolio-a4334',
    storageBucket: 'eatfolio-a4334.firebasestorage.app',
    iosClientId:
        '413718822127-7nq6gpfi7gg4dt9ns8ueaom8tgsa3hj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.eatfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFHMflsw3hvQA73fB6Ddm2nFGxtJI4qGY',
    appId: '1:413718822127:web:9a26e12fe424bec1fdaf1a',
    messagingSenderId: '413718822127',
    projectId: 'eatfolio-a4334',
    authDomain: 'eatfolio-a4334.firebaseapp.com',
    storageBucket: 'eatfolio-a4334.firebasestorage.app',
    measurementId: 'G-XDYKTDS1HL',
  );
}
